### ISSUE TITLE
[Question] 一些疑問

### ISSUE THREAD

**Issue by EvanHsieh0415** [AmarokIce/WithJson#1]
- [x] 1. Forge 1.7.10的`Block.json`与其他资料是否与Fabric的使用方法一致
- [x] 2. 除了`DeleteRecipe`和`Biomes`之外是否Fabric皆可使用
- [x] 3. 为什么仅`ItemWeapons`为复数，个人认为皆为复数为最优解
- [x] 4. 为什么`info.json`不予同资料夹的其他文件一样首字大写
- [x] 5. 为什么`Recipe.json`里的配方`count`等的值为String而不是原生的Integer
- [x] 6. `Recipe.json`是否支援其他模组的配方，如Create、Farmer's Delight
- [x] 7. `localization_name`在`lang/en_us.json`中的key为何，或相关的标准
- [x] 9. 为什么在Forge 1.7.10版中`Block.json`的`hard`是Integer，而在Fabric中却是Float
- [x] 10. `localization_name`、`texture_name`是否支援调用其他模组的资源
- [x] 11. 是否能提供全部value的默认值
- [x] 12. 待补...

**Comment by AmarokIce** [comment]
1. 是的，可以说基本一致
 2. Recipe与Biomes相关都应该使用数据包，Fabric 1.16中对Biomes的支持是计划的一部分
 3. 感谢反馈！事实上是编写时的疏忽导致的，不过考虑到兼容性，可能会重新设计成可加或不加
 4. 计划中会让这些内容大小写不敏感，至于为什么这么设计... 说实话我也不知道(x
 5. 解析Map时使用String，我担心如果使用Any（Object）可能会在某些不规范的编写中出现问题，当然的，未来会以保证兼容性的情况下使其达到理想的效果
 6. 数据包是完全兼容的，而1.7.10中Recipe.json也是完全兼容的！只要注册名和文件的结构填写没有问题
 7. 和其他任意一个模组一样，lang文件的key的组合是“类型.MODID.键名”，键名则是注册名中物品名称的部分，比如注册名`pineapple:pineapple_item` 这个物品的lang键为 `item.pineapple.pineapple_item` ，如果它是一个方块，那么它应该是 `block.pineapple.pineapple_item` 
 9. 1.7.10的Block构造器便是如此，即便提供了Float，在1.7.10中最终也必须再强转型为Integer
 10. lang恐怕不行，除非那个模组的assets下有我们创建的模组的modid文件夹，而texture_name是完全可以的！
 11. 这个我不是很明白，默认值的期望是什么样的？

**Comment by EvanHsieh0415** [comment]
> 10. 这个我不是很明白，默认值的期望是什么样的？

像是原版的recipe的count默认为1，若没填上则会使用默认值，我希望也能得知WithJson的相关内容

**Comment by AmarokIce** [comment]
暂时没有默认值的设定，如果缺少内容的话会跳过本次解析
这闻起来是个不错的主意，未来会新增空值时以默认值解析

**Comment by EvanHsieh0415** [comment]
~~順帶一提我覺得可以把我問的這些加到README裡面~~

**Comment by AmarokIce** [comment]
下一次更新会整理Readme
